export const skills = [
	{
		name: "HTML5",
		id: 1,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
		alt: "HTML 5 Icon",
		proficiency: 85,
	},
	{
		name: "CSS3",
		id: 2,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
		alt: "CSS3 Icon",
		proficiency: 85,
	},
	{
		name: "JavaScript",
		id: 3,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
		alt: "JavaScript Icon",
		proficiency: 85,
	},
	{
		name: "TypeScript",
		id: 4,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
		alt: "TypeScript Icon",
		proficiency: 75,
	},
	{
		name: "React",
		id: 5,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
		alt: "React Icon",
		proficiency: 85,
	},
	{
		name: "Vue",
		id: 6,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg",
		alt: "Vue.js Icon",
		proficiency: 50,
	},
	{
		name: "Svelte",
		id: 7,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg",
		alt: "Svelte Icon",
		proficiency: 45,
	},
	{
		name: "Git",
		id: 8,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
		alt: "Git Icon",
		proficiency: 55,
	},
	{
		name: "Node.js",
		id: 9,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
		alt: "Node.js Icon",
		proficiency: 55,
	},
	{
		name: "Figma",
		id: 10,
		src: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg",
		alt: "Figma icon",
		proficiency: 75,
	},
];
